apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: workshops.orchestra.io
spec:
  group: orchestra.io
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              name:
                type: string
                description: "Workshop instance name"
              duration:
                type: string
                default: "4h"
                description: "Workshop duration (e.g., 4h, 2h30m)"
              image:
                type: string
                default: "rocker/rstudio:latest"
                description: "RStudio Docker image to use"
              resources:
                type: object
                properties:
                  cpu:
                    type: string
                    default: "1"
                  memory:
                    type: string
                    default: "2Gi"
                  cpuRequest:
                    type: string
                    default: "500m"
                  memoryRequest:
                    type: string
                    default: "1Gi"
                description: "Resource limits for the workshop"
              storage:
                type: object
                properties:
                  size:
                    type: string
                    default: "10Gi"
                  storageClass:
                    type: string
                description: "Storage configuration"
              ingress:
                type: object
                properties:
                  host:
                    type: string
                  annotations:
                    type: object
                    additionalProperties:
                      type: string
                description: "Ingress configuration"
            required:
            - name
          status:
            type: object
            properties:
              phase:
                type: string
                enum: ["Pending", "Creating", "Ready", "Running", "Terminating", "Failed"]
              url:
                type: string
              createdAt:
                type: string
                format: date-time
              expiresAt:
                type: string
                format: date-time
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                    reason:
                      type: string
                    message:
                      type: string
                    lastTransitionTime:
                      type: string
                      format: date-time
  scope: Namespaced
  names:
    plural: workshops
    singular: workshop
    kind: Workshop
    shortNames:
    - ws
